### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Kocik** [cjhooker/eote-dice-roller#14]
Hi,
as Hangout tools will stop working soon, I started to code my version of dice roller.
You have all of the images of sides of the dices and symbols and they look real nice too! It would help me a great deal if I could use them :)

Regards,
Kocik

**Comment by cjhooker** [comment]
Yeah, definitely feel free to use them!

How are you implementing your dice roller? Is it just going to be a standalone application?

**Comment by Kocik** [comment]
Thanks a lot :)
I'm writing a web app. React on the front and php on the backend. Maybe will try to wrap it as a browser plugin later or Electron app.
I didn't have much time to work on it yet, but I will get back to it soon. Here is a link to my repo: https://github.com/Kocik/eote-dice-roller
